### ISSUE TITLE
Unable to read data, always showing waiting.

### ISSUE THREAD

**Issue by Benprooo** [valamicorp/top100token-ape-bot#12]
Yesterday, there was no problem when using it. Today, after changing the version, it appeared that the data could not be read, and the problem of waiting was always displayed. How should I operate?
![image](https://user-images.githubusercontent.com/81796525/135798638-1a86301b-3b1b-4da8-9326-057001a2df76.png)

**Comment by Benprooo** [comment]
Excuse me, how can I uninstall it and reinstall it? It's just like the first time I opened the software and jumped out of the window to fill in the private key. I think I screwed up myself.

**Comment by valamidev** [comment]
You can find add valid PrivateKey manual, or you can delete the settings folder of the app:

```
C:\Users\<you>\AppData\Local\top100token-ape-bot
```

**Comment by Benprooo** [comment]
Thank you very much for your reply. But it's very strange that I can't find it under this path. I'll look it up again.

**Comment by Benprooo** [comment]
![image](https://user-images.githubusercontent.com/81796525/135886093-9a7eb69e-604d-48ce-8908-5cace5aba782.png)

**Comment by Benprooo** [comment]
I found it. It was hidden in this place.C:\Users\aa\AppData\Roaming\top100token-ape-bot

**Comment by Benprooo** [comment]
Thank you very much. After deleting the folder and reopening the software, it returned to normal again. You are a great and kind developer and look forward to your next update. Wish you success in your work.
