### ISSUE TITLE
withdrow BNB funds from the wallet

### ISSUE THREAD

**Issue by Kiloger** [valamicorp/top100token-ape-bot#15]
hey i need to withdrow my bnb out from the app wallet how do i do this?

**Comment by Kiloger** [comment]
I forget to save it please help meee

**Comment by Kiloger** [comment]
> You can import the PrivateKey into MetaMask wallet, I hope u saved it :)
> 
> In case of u forget to save.... please reply and I will create a button into the next release which allow send the BNB to external account.

I forgotten to save it can you help me

**Comment by valamidev** [comment]
You can import the PrivateKey into MetaMask wallet, I hope u saved it :)

In case of u forget to save.... please reply and I will create a button into the next release which allow send the BNB to external account.

**Comment by Kiloger** [comment]
> You can import the PrivateKey into MetaMask wallet, I hope u saved it :)
> 
> In case of u forget to save.... please reply and I will create a button into the next release which allow send the BNB to external account.

Where your app save the Js file that I can import to metamask ?

**Comment by valamidev** [comment]
> > You can import the PrivateKey into MetaMask wallet, I hope u saved it :)
> > In case of u forget to save.... please reply and I will create a button into the next release which allow send the BNB to external account.
> 
> Where your app save the Js file that I can import to metamask ?

The Config file is encrypted :)

There is a Button in the new version, which will show your private key.
