### ISSUE TITLE
I have configured the telegraph session. Why does the program not respond? Are there any other restrictions on the message format in the group

### ISSUE THREAD

**Issue by kimiboby** [valamicorp/top100token-ape-bot#16]
I found that in the console, the program did receive the message, but it seemed unable to interpret it
![image](https://user-images.githubusercontent.com/56426273/140712263-5558afc6-768f-4bef-9175-1a7944cddd84.png)

**Comment by kimiboby** [comment]
![image](https://user-images.githubusercontent.com/56426273/140711208-52102fdc-d034-4edc-964c-1764a81c2de2.png)

**Comment by valamidev** [comment]
Yes, you are right has an additional check so the message content so having address is not enough, I will add an option to configure.

**Comment by kimiboby** [comment]
Mr. The next version cannot add a slippage setting

**Comment by valamidev** [comment]
Feel free to make a Pull Request.
