### ISSUE TITLE
Something went wrong and received less tokens

### ISSUE THREAD

**Issue by fearslayer** [valamicorp/top100token-ape-bot#17]
Today i bought 2.2 bnb($1,424.34) of BNX (0x8c851d1a123ff703bd1f9dabe631b69902df5f97) but i received only 1.9 tokens($291.18)
, is there anything wrong on the bot?

https://bscscan.com/tx/0x64b1328e07110a36a57875d0314d8a9206de504cc3fddfbb64aae3902adc7745

![image](https://user-images.githubusercontent.com/181380/140794635-e76401d5-f816-41c5-ac71-bde6cb979ad7.png)

**Comment by fearslayer** [comment]
This was caused by the bot :( the bot has multihop turned off as default so it wont converted to busd and bougth the token as the bnb LP is low i paid this amount, this was a huge punch on me, thanks for the bot but take care of this thing to not made other ppl lose money too
![image](https://user-images.githubusercontent.com/181380/140807911-f4008926-fcc1-4077-97f7-d976f6179227.png)
![image](https://user-images.githubusercontent.com/181380/140807937-a797a3b1-cac3-4b8f-bcd9-03a1a84eb838.png)

**Comment by valamidev** [comment]
I hope you read the section:

**DeFi APE bot for PancakeSwap, UniSwapV2, CheapSwap,Quickswap, SpookySwap, DevEthSwap. This tool made for education purposes, use it for your own risk.**

That is the risk to mention.

**Comment by fearslayer** [comment]
Yeah, my bad on that, but i am posting this to "fix future cases :) lesson learn, the bot is amazing btw, just need to fix this and is perfect
