### ISSUE TITLE
Ape Address

### ISSUE THREAD

**Issue by nnnikolay** [valamicorp/top100token-ape-bot#19]
Hi there,

I have a quick question, do  I understand correctly that I need to find and fill in the token/contract address manually from coinmarketcup, or is the bot supposed to do that?

**Comment by valamidev** [comment]
The bot do it automatically if you provide a coinmarketcap API key, or setup the telegram plugin.

**Comment by nnnikolay** [comment]
If the bot does it automatically, what for is the field and button there?
