### ISSUE TITLE
Custom GAS price

### ISSUE THREAD

**Issue by lwtz** [valamicorp/top100token-ape-bot#21]
How to configure the gas to not have losses in transactions?

Or, what would be the best gas for the transactions?

I know you have the option to configure the gas, but what values are indicated? Is there any kind of table to know?

**Comment by system32uwu** [comment]
Depending on the chain you're using you can use a GAS tracker, which would be a nice feature to have implemented in this project.
I use the polygon chain, so I check GAS here: https://polygonscan.com/gastracker/
