### ISSUE TITLE
pls add Cronos chain 

### ISSUE THREAD

**Issue by L2b2n** [valamicorp/top100token-ape-bot#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
 id: 'cronos',
    name: 'Cronos',
    slug: "CRO",
    logo: 'https://ibb.co/LzjCC0W',
    scanLogo: './assets/none.png',
    router: "0xcd7d16fB918511BF7269eC4f48d61D79Fb26f918",
    factory: "0x73A48f8f521EB31c55c0e1274dB0898dE599Cb11",
    rcpAddress: "https://rpc-cronos.crypto.org",
    defaultGas: "5000000000",
    wCoin: '0x5C7F8A570d578ED84E63fdFA7b1eE72dEae1AE23',
    testContract: '0xccae06ec0787c07d7df5a60856c73a113fc7cf9a',
    contractExplorer: (address: string) => `https://cronos.crypto.org/explorer/tokens/${address}`,
    chartLink:  (address: string) => `https://dexscreener.com/cronos/${address}`,
    swapLink:  (address: string) => `https://app.cronaswap.org/swap?outputCurrency=${address}`

**Comment by valamidev** [comment]
Thx, added
