### ISSUE TITLE
Transaction wait for receipt loop

### ISSUE THREAD

**Issue by hungtrungthinh** [valamicorp/top100token-ape-bot#26]
<img width="516" alt="Screen Shot 2021-12-14 at 02 50 28" src="https://user-images.githubusercontent.com/6177853/145878694-679458bf-6c00-4107-972a-859e84bd4f49.png">

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by valamidev** [comment]
It is not an error, it is a verbose logging for transaction tracking.
